select = ["ALL"]
target-version = "py311"

line-length = 120


ignore = [
    "ANN101", # PERM: this is only usefull in large classes (https://docs.astral.sh/ruff/rules/missing-type-self/)
    "ANN102", # PERM: this is only usefull in large classes (https://docs.astral.sh/ruff/rules/missing-type-cls/)
    "D400",   # PERM: I don't do this (https://docs.astral.sh/ruff/rules/ends-in-period/)
    "D415",   # PERM: I don't do this (https://docs.astral.sh/ruff/rules/ends-in-punctuation/)
    "G004",   # PERM: I use f-string in loogin (https://docs.astral.sh/ruff/rules/logging-f-string/)
    "TD003",  # PERM: I don't have issur traking in this project (https://docs.astral.sh/ruff/rules/missing-todo-link/)
]

[lint.pydocstyle]
convention = "google"

[lint.flake8-builtins]
builtins-ignorelist = ["id"]
