---
version: "3.0"
services:
  arch:
    build: .
    container_name: arch
    environment:
      - TZ=America/New_York
    ports:
      - 22:22
    volumes:
      - /home/r2r0m0c0/:/data
    hostname: Arch-Sandboxes
    restart: unless-stopped
