---
version: "3"
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - TZ=Etc/EST
    volumes:
      - /ZFS/Media/Docker/Docker/Storage/freshrss:/config
    ports:
      - 8800:80
    restart: unless-stopped
