---
version: "3.0"
services:
  ubuntu:
    build: .
    container_name: ubuntu
    environment:
      - TZ=America/New_York
    ports:
      - 22:22
    volumes:
      - /home/r2r0m0c0/:/data
    hostname: Ubuntu-Sandboxes
    restart: unless-stopped
