---
version: "3"
services:
  endlessh:
    image: lscr.io/linuxserver/endlessh:latest
    container_name: endlessh
    environment:
      - PUID=998
      - PGID=100
      - MSDELAY=10000
      - MAXLINES=32
      - MAXCLIENTS=4096
      - LOGFILE=true
    volumes:
      - /ZFS/Media/Docker/Docker/Storage/endlessh:/config
    ports:
      - 22:2222
    restart: unless-stopped
