---
version: "3.0"
services:
  debian:
    build: .
    container_name: debian
    environment:
      - TZ=America/New_York
    ports:
      - 22:22
    volumes:
      - /home/r2r0m0c0/:/data
    hostname: Debian-Sandboxes
    restart: unless-stopped
