---
version: "3"
services:
  arch_mirror:
    image: ubuntu/apache2:latest
    container_name: arch_mirror
    environment:
      - TZ=Etc/EST
    ports:
      - 800:80
    volumes:
      - /ZFS/Main/Mirror/:/data
      - /ZFS/Main/Docker/Docker/templates/file_server/sites/:/etc/apache2/sites-enabled/
    restart: unless-stopped
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    user: "998:998"
    environment:
      - TZ=Etc/EST
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
    volumes:
      - /ZFS/Main/Docker/Docker/jeeves-jr/haproxy/cloudflare.pem:/etc/ssl/certs/cloudflare.pem
      - /ZFS/Main/Docker/Docker/jeeves-jr/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - arch_mirror
    restart: unless-stopped
  cloud_flare_tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloud_flare_tunnel
    command: tunnel run
    env_file:
      - cloudflare_tunnel.env
    depends_on:
      - haproxy
    restart: unless-stopped
