# Multi line secret ma not work in the gihthub actions vscode interface
on:
  push:
    branches:
      - main
    paths:
      - "jeeves/**"
      - ".github/workflows/jeeves_deploy.yml"
      - "templates/**"
      - "scripts/**"
  pull_request:
    branches:
      - main
    paths:
      - "jeeves/**"
      - ".github/workflows/jeeves_deploy.yml"
      - "templates/**"
      - "scripts/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest --doctest-modules --junitxml=junit/test-results.xml --cov=./scripts --cov-report=xml --cov-report=html --cov-branch

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: ZeroTier
        uses: zerotier/github-action@main
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

      - name: Deploy to jeeves
        uses: appleboy/ssh-action@master
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          TUNNEL_TOKEN: ${{ secrets.JEEVES_TUNNEL_TOKEN }}
          PIA_USERNAME: ${{ secrets.PIA_USERNAME }}
          PIA_PASSWORD: ${{ secrets.PIA_PASSWORD }}
          LAN_NETWORK: ${{ secrets.LAN_NETWORK }}

        with:
          host: ${{ secrets.JEEVES_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.JEEVES_SSH_PORT }}
          script: |
            git -C /ZFS/Media/Docker/Docker pull
            python3 /ZFS/Media/Docker/Docker/scripts/docker_update.py --machine_name jeeves
          envs: POSTGRES_USER, POSTGRES_PASSWORD, TUNNEL_TOKEN, PIA_USERNAME, PIA_PASSWORD, LAN_NETWORK
