# Multi line secret ma not work in the gihthub actions vscode interface
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your build steps here

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: ZeroTier
        uses: zerotier/github-action@v1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        env:
          TUNNEL_TOKEN: ${{ secrets.JEEVES_JR_TUNNEL_TOKEN }}

        with:
          host: ${{ secrets.JEEVES_JR_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            git -C /ZFS/Main/Docker/Docker pull
            python3 /ZFS/Main/Docker/Docker/docker_update.py
          envs: TUNNEL_TOKEN
