---
version: "3"
services:
  influxdb:
    image: influxdb:2.6
    container_name: influxdb
    environment:
      TZ: "America/New_York"
      INFLUXDB_DATA_QUERY_LOG_ENABLED: "false"
      INFLUXDB_REPORTING_DISABLED: "true"
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
    ports:
      - "8086:8086"
    volumes:
      - /ZFS/Media/DataBases/Influxdb:/var/lib/influxdb2
    logging:
      driver: "json-file"
      options:
        max-size: "1000M"
    restart: unless-stopped
